In [3]:
import cv2
from pathlib import Path

img_path = Path(
    r"/home/ubuntu/桌面/project/c50a_calibrator/datasets/calibr_c50A/frame_1744866517429.jpg"
)
img = cv2.imread(str(img_path))

In [4]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imwrite("gray.jpg", gray)
board_size = (5, 6)
ret, corners = cv2.findChessboardCorners(gray, board_size, None)

In [3]:
print(corners)

[[[221.99847 303.43433]]

 [[266.64038 303.10632]]

 [[311.56973 302.48215]]

 [[357.20752 302.30386]]

 [[402.35828 301.51172]]

 [[211.4727  325.93433]]

 [[259.63907 325.42072]]

 [[307.59128 325.46448]]

 [[357.219   325.3133 ]]

 [[405.91766 324.63037]]

 [[198.48196 353.08826]]

 [[251.10506 352.38324]]

 [[303.55792 351.6766 ]]

 [[357.39755 351.52   ]]

 [[410.4457  351.50043]]

 [[183.47038 384.7127 ]]

 [[241.19244 384.20966]]

 [[298.9871  384.11572]]

 [[357.0171  383.7118 ]]

 [[415.5542  383.61414]]

 [[165.24348 423.4248 ]]

 [[228.66281 423.35947]]

 [[292.7175  423.14243]]

 [[357.06613 423.29163]]

 [[421.6724  423.43008]]

 [[143.56717 469.90482]]

 [[213.5975  470.59808]]

 [[284.83887 471.20898]]

 [[357.35367 471.51266]]

 [[429.54318 471.51917]]]


In [4]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
win_size = (11, 11)
zeroZone = (-1, -1)
corners2 = cv2.cornerSubPix(gray, corners, win_size, zeroZone, criteria)

In [5]:
print(corners2)

[[[222.09065 303.3973 ]]

 [[266.56256 303.035  ]]

 [[311.61142 302.5156 ]]

 [[357.13202 302.036  ]]

 [[402.42044 301.60345]]

 [[211.4312  325.8685 ]]

 [[259.60327 325.54428]]

 [[308.1962  325.4289 ]]

 [[357.11243 325.2422 ]]

 [[406.05603 324.72256]]

 [[198.70389 352.92563]]

 [[251.07881 352.40378]]

 [[303.72467 351.97784]]

 [[357.1679  351.65887]]

 [[410.44894 351.5587 ]]

 [[183.7162  384.66156]]

 [[241.11896 384.25955]]

 [[298.60498 383.98184]]

 [[357.09958 383.86343]]

 [[415.55844 383.71555]]

 [[165.37856 423.28223]]

 [[228.53647 423.231  ]]

 [[292.52304 423.10495]]

 [[357.1168  423.12595]]

 [[422.14868 423.30624]]

 [[143.02248 469.916  ]]

 [[213.24045 470.68802]]

 [[284.4202  471.18613]]

 [[357.15625 471.81625]]

 [[429.73462 471.5825 ]]]


In [14]:
import numpy as np

objp = np.zeros((board_size[0] * board_size[1], 3), np.float32)
objp[:, :2] = np.mgrid[0 : board_size[0], 0 : board_size[1]].T.reshape(-1, 2)

# 定义棋盘格的尺寸和每个方格的大小（单位：米）
board_height = 6  # 棋盘格的行数
board_width = 5  # 棋盘格的列数
square_size = 0.16  # 每个方格的边长，例如 2.5 厘米

# 初始化一个空的列表，用于存储三维坐标点
object_points = []

# 生成棋盘格的三维坐标点
for i in range(board_height):
    for j in range(board_width):
        # x = -i * square_size + 3.39-0.254
        # y = -j * square_size + 0.543
        x = -i * square_size + 1.60 + 0.03 + 6 * 0.16
        y = -j * square_size + 0.264 - 0.16 + 0.2685
        z = -0.07
        object_points.append([x, y, z])

# 将列表转换为 NumPy 数组，并指定数据类型为 float32
object_points_array = np.array(object_points, dtype=np.float32)

In [15]:
print(object_points_array)

[[ 2.59    0.3725 -0.07  ]
 [ 2.59    0.2125 -0.07  ]
 [ 2.59    0.0525 -0.07  ]
 [ 2.59   -0.1075 -0.07  ]
 [ 2.59   -0.2675 -0.07  ]
 [ 2.43    0.3725 -0.07  ]
 [ 2.43    0.2125 -0.07  ]
 [ 2.43    0.0525 -0.07  ]
 [ 2.43   -0.1075 -0.07  ]
 [ 2.43   -0.2675 -0.07  ]
 [ 2.27    0.3725 -0.07  ]
 [ 2.27    0.2125 -0.07  ]
 [ 2.27    0.0525 -0.07  ]
 [ 2.27   -0.1075 -0.07  ]
 [ 2.27   -0.2675 -0.07  ]
 [ 2.11    0.3725 -0.07  ]
 [ 2.11    0.2125 -0.07  ]
 [ 2.11    0.0525 -0.07  ]
 [ 2.11   -0.1075 -0.07  ]
 [ 2.11   -0.2675 -0.07  ]
 [ 1.95    0.3725 -0.07  ]
 [ 1.95    0.2125 -0.07  ]
 [ 1.95    0.0525 -0.07  ]
 [ 1.95   -0.1075 -0.07  ]
 [ 1.95   -0.2675 -0.07  ]
 [ 1.79    0.3725 -0.07  ]
 [ 1.79    0.2125 -0.07  ]
 [ 1.79    0.0525 -0.07  ]
 [ 1.79   -0.1075 -0.07  ]
 [ 1.79   -0.2675 -0.07  ]]


In [32]:
print(objp)

[[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [2. 1. 0.]
 [3. 1. 0.]
 [4. 1. 0.]
 [0. 2. 0.]
 [1. 2. 0.]
 [2. 2. 0.]
 [3. 2. 0.]
 [4. 2. 0.]
 [0. 3. 0.]
 [1. 3. 0.]
 [2. 3. 0.]
 [3. 3. 0.]
 [4. 3. 0.]
 [0. 4. 0.]
 [1. 4. 0.]
 [2. 4. 0.]
 [3. 4. 0.]
 [4. 4. 0.]
 [0. 5. 0.]
 [1. 5. 0.]
 [2. 5. 0.]
 [3. 5. 0.]
 [4. 5. 0.]]


In [33]:
objp = object_points_array
fx = 571
fy = 571
cx = 332.729
cy = 231.085
distortion_coefficients = np.array([0, 0, 0, 0, 0])
camera_matrix = np.array(
    [[fx, 0, cx], [0, fy, cy], [0, 0, 1]]
)  # fx, fy, cx, cy 分别为焦距和主点坐标
# 世界到相机
success, rvec, tvec = cv2.solvePnP(
    objp, corners2, camera_matrix, distortion_coefficients
)

In [34]:
print(rvec)

[[ 1.46924231]
 [-1.44260286]
 [ 0.96573964]]


In [35]:
print(tvec)

[[ 0.01136425]
 [ 1.43846152]
 [-1.16591992]]


In [36]:
R, _ = cv2.Rodrigues(rvec)

In [37]:
print(R)

[[ 0.0404258  -0.9986721  -0.03193429]
 [-0.35103855  0.01572768 -0.93622891]
 [ 0.93548794  0.04905797 -0.3499366 ]]


In [38]:
P_w = np.array([[3.39], [0.543], [0]])  # 世界坐标 (0, 1, 2)
P_c = np.dot(R, P_w) + tvec

In [39]:
print(P_c)

[[-0.39387123]
 [ 0.25698095]
 [ 2.03202268]]


In [40]:
P_p = np.dot(camera_matrix, P_c)
print(camera_matrix)
print(P_p)

[[571.      0.    332.729]
 [  0.    571.    231.085]
 [  0.      0.      1.   ]]
[[451.21240589]
 [616.30608299]
 [  2.03202268]]


In [41]:
K = camera_matrix
u = (K[0, 0] * P_c[0] / P_c[2]) + K[0, 2]  # u 坐标
v = (K[1, 1] * P_c[1] / P_c[2]) + K[1, 2]  # v 坐标
print(u)
print(v)

[222.05087056]
[303.29685193]


In [42]:
def calibr_camera(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    board_size = (5, 6)
    ret, corners = cv2.findChessboardCorners(gray, board_size, None)
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
    win_size = (11, 11)
    zeroZone = (-1, -1)
    corners2 = cv2.cornerSubPix(gray, corners, win_size, zeroZone, criteria)
    points = []
    for i in range(corners2.shape[0]):
        point = tuple(corners2[i, 0])  # 提取 (x, y) 坐标
        points.append(point)  # 将坐标存储到列表中
    return points

In [43]:
res = calibr_camera(img)

In [44]:
print(res)

[(222.09065, 303.3973), (266.56256, 303.035), (311.61142, 302.5156), (357.13202, 302.036), (402.42044, 301.60345), (211.4312, 325.8685), (259.60327, 325.54428), (308.1962, 325.4289), (357.11243, 325.2422), (406.05603, 324.72256), (198.70389, 352.92563), (251.07881, 352.40378), (303.72467, 351.97784), (357.1679, 351.65887), (410.44894, 351.5587), (183.7162, 384.66156), (241.11896, 384.25955), (298.60498, 383.98184), (357.09958, 383.86343), (415.55844, 383.71555), (165.37856, 423.28223), (228.53647, 423.231), (292.52304, 423.10495), (357.1168, 423.12595), (422.14868, 423.30624), (143.02248, 469.916), (213.24045, 470.68802), (284.4202, 471.18613), (357.15625, 471.81625), (429.73462, 471.5825)]


In [45]:
print(corners2.shape)

(30, 1, 2)


In [46]:
def pixel_to_world(u, v, K, R, t):
    fx, fy = K[0, 0], K[1, 1]
    cx, cy = K[0, 2], K[1, 2]
    r11, r12, r13 = R[0]
    r21, r22, r23 = R[1]
    r31, r32, r33 = R[2]
    tx, ty, tz = t

    # 构造系数矩阵
    A1 = u * r31 - fx * r11 - cx * r31
    B1 = u * r32 - fx * r12 - cx * r32
    C1 = fx * tx + cx * tz - u * tz

    A2 = v * r31 - fy * r21 - cy * r31
    B2 = v * r32 - fy * r22 - cy * r32
    C2 = fy * ty + cy * tz - v * tz

    # 解线性方程组
    denominator = A1 * B2 - A2 * B1
    if denominator == 0:
        return None  # 无解或无穷解
    X = (B1 * C2 - B2 * C1) / denominator
    Y = (A2 * C1 - A1 * C2) / denominator
    return (X, Y, 0)

In [26]:
# 266.56256,303.035
# 250.95315708,352.51293594
p_world = pixel_to_world(266.56256, 303.035, K, R, tvec)

In [47]:
print(p_world)

(array([3.42248283]), array([-1.94705788]), 0.0)


In [48]:
import numpy as np


def pixel_to_world(u, v, K, R, t):
    fx, fy = K[0, 0], K[1, 1]
    cx, cy = K[0, 2], K[1, 2]
    r11, r12, r13 = R[0, 0], R[0, 1], R[0, 2]
    r21, r22, r23 = R[1, 0], R[1, 1], R[1, 2]
    r31, r32, r33 = R[2, 0], R[2, 1], R[2, 2]
    tx, ty, tz = t[0], t[1], t[2]

    # 构造系数矩阵（注意符号一致性）
    A1 = (u - cx) * r31 - fx * r11
    B1 = (u - cx) * r32 - fx * r12
    C1 = fx * tx + (cx - u) * tz

    A2 = (v - cy) * r31 - fy * r21
    B2 = (v - cy) * r32 - fy * r22
    C2 = fy * ty + (cy - v) * tz

    # 解线性方程组 AX = B
    A = np.array([[A1, B1], [A2, B2]])
    B = np.array([C1, C2])
    try:
        X, Y = np.linalg.solve(A, B)
    except np.linalg.LinAlgError:
        return None  # 矩阵奇异或无解

    # 检查地平面点是否在相机前方
    denominator = r31 * X + r32 * Y + tz
    if denominator <= 0:
        return None  # 点在相机后方或投影无效

    return (X, Y, 0.0)

In [53]:
# [222.05087056]
# [303.29685193]
# [[266.56256 303.035  ]]
#  [[311.61142 302.5156 ]]
p_world = pixel_to_world(311.61142, 302.5156, K, R, tvec)
print(p_world)

(array([3.38938778]), array([0.22322936]), 0.0)


In [5]:
object_points = [
    [160 + 57, 80 - 24.5, 0],
    [4 * 80 - 8, 80 + 45.6, 0],
    [5 * 80 + 20.6, 80 + 49.5, 0],
    [7 * 80 + 16, 80 + 19, 0],
    [7 * 80 + 33, -5, 0],
    [7 * 80 + 33, -50, 0],
    [7 * 80 + 34, -80 - 74, 0],
    [5 * 80 + 5, -31, 0],
    [4 * 80 + 22.6, -72.6, 0],
    [3 * 80 + 40, -31.5, 0],
]

In [6]:
for i in range(len(object_points)):
    point = object_points[i]
    point[0] = point[0]
    point[1] = point[1] + 26.85
    point[2] = point[2] - 7
for i in range(len(object_points)):
    point = object_points[i]
    point[0] = point[0] * 0.01
    point[1] = point[1] * 0.01
    point[2] = point[2] * 0.01
print(object_points)

[[2.17, 0.8235, -0.07], [3.12, 1.5245, -0.07], [4.206, 1.5635, -0.07], [5.76, 1.2585, -0.07], [5.93, 0.21850000000000003, -0.07], [5.93, -0.23149999999999998, -0.07], [5.94, -1.2715, -0.07], [4.05, -0.04149999999999999, -0.07], [3.426, -0.45749999999999996, -0.07], [2.8000000000000003, -0.046499999999999986, -0.07]]


In [8]:
object_points = [
    [254.8, 20, 0],
    [254.8, -70, 0],
    [165, 20, 0],
    [165, -70, 0],
    [415, -65, 0],
    [415, -155, 0],
    [325, -65, 0],
    [325, -155, 0],
    [560, 200, 0],
    [560, 110.4, 0],
    [560, 30, 0],
    [560, -60, 0],
    [560, -135.2, 0],
    [560, -225, 0],
]
for i in range(len(object_points)):
    point = object_points[i]
    point[0] = point[0]
    point[1] = point[1] + 26.85
    point[2] = point[2] - 7
for i in range(len(object_points)):
    point = object_points[i]
    point[0] = point[0] * 0.01
    point[1] = point[1] * 0.01
    point[2] = point[2] * 0.01
    print(point)
print(object_points)

[2.548, 0.4685, -0.07]
[2.548, -0.4315, -0.07]
[1.6500000000000001, 0.4685, -0.07]
[1.6500000000000001, -0.4315, -0.07]
[4.15, -0.3815, -0.07]
[4.15, -1.2815, -0.07]
[3.25, -0.3815, -0.07]
[3.25, -1.2815, -0.07]
[5.6000000000000005, 2.2685, -0.07]
[5.6000000000000005, 1.3725, -0.07]
[5.6000000000000005, 0.5685, -0.07]
[5.6000000000000005, -0.3315, -0.07]
[5.6000000000000005, -1.0835, -0.07]
[5.6000000000000005, -1.9815, -0.07]
[[2.548, 0.4685, -0.07], [2.548, -0.4315, -0.07], [1.6500000000000001, 0.4685, -0.07], [1.6500000000000001, -0.4315, -0.07], [4.15, -0.3815, -0.07], [4.15, -1.2815, -0.07], [3.25, -0.3815, -0.07], [3.25, -1.2815, -0.07], [5.6000000000000005, 2.2685, -0.07], [5.6000000000000005, 1.3725, -0.07], [5.6000000000000005, 0.5685, -0.07], [5.6000000000000005, -0.3315, -0.07], [5.6000000000000005, -1.0835, -0.07], [5.6000000000000005, -1.9815, -0.07]]


In [9]:
object_points = [
    [254.8, 20, 0],
    [254.8, -70, 0],
    [165, -70, 0],
    [165, 20, 0],

    [415, -65, 0],
    [415, -155, 0],
    [325, -155, 0],
    [325, -65, 0],

    [414.6,105, 0],
    [414.6 ,15, 0],
    [325, 15, 0],
    [325, 105, 0],

    [560, 195, 90],
    [560, 105, 90],
    [560, 105, 0],
    [560, 195, 0],

    [560, 25, 90],
    [560, -64, 90],
    [560, -64, 0],
    [560, 25, 0],

    [560, -135, 90],
    [560, -225, 90],
    [560, -225, 0],
    [560, -135, 0],
]
for i in range(len(object_points)):
    point = object_points[i]
    point[0] = point[0]
    point[1] = point[1] + 26.85
    point[2] = point[2] - 7
for i in range(len(object_points)):
    point = object_points[i]
    point[0] = point[0] * 0.01
    point[1] = point[1] * 0.01
    point[2] = point[2] * 0.01
    print(point)
print(object_points)

[2.548, 0.4685, -0.07]
[2.548, -0.4315, -0.07]
[1.6500000000000001, -0.4315, -0.07]
[1.6500000000000001, 0.4685, -0.07]
[4.15, -0.3815, -0.07]
[4.15, -1.2815, -0.07]
[3.25, -1.2815, -0.07]
[3.25, -0.3815, -0.07]
[4.146, 1.3185, -0.07]
[4.146, 0.41850000000000004, -0.07]
[3.25, 0.41850000000000004, -0.07]
[3.25, 1.3185, -0.07]
[5.6000000000000005, 2.2185, 0.8300000000000001]
[5.6000000000000005, 1.3185, 0.8300000000000001]
[5.6000000000000005, 1.3185, -0.07]
[5.6000000000000005, 2.2185, -0.07]
[5.6000000000000005, 0.5185000000000001, 0.8300000000000001]
[5.6000000000000005, -0.3715, 0.8300000000000001]
[5.6000000000000005, -0.3715, -0.07]
[5.6000000000000005, 0.5185000000000001, -0.07]
[5.6000000000000005, -1.0815000000000001, 0.8300000000000001]
[5.6000000000000005, -1.9815, 0.8300000000000001]
[5.6000000000000005, -1.9815, -0.07]
[5.6000000000000005, -1.0815000000000001, -0.07]
[[2.548, 0.4685, -0.07], [2.548, -0.4315, -0.07], [1.6500000000000001, -0.4315, -0.07], [1.6500000000000001,