# Pinhole Camera Calibration
## 1. Introduction
### 1.1 Why Calibration?

### 1.2 How to Calibrate?
### 1.3 Calibrate results and how to use them?
## 2. Calibration principle
### 2.1 
## 3.Calibration process

In [10]:
import numpy as np
import cv2 as cv
import glob
import matplotlib.pyplot as plt
import os

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('calibration_data/opencv_sample_data/left*.jpg')
print(images)


['calibration_data/opencv_sample_data/left13.jpg', 'calibration_data/opencv_sample_data/left08.jpg', 'calibration_data/opencv_sample_data/left05.jpg', 'calibration_data/opencv_sample_data/left01.jpg', 'calibration_data/opencv_sample_data/left11.jpg', 'calibration_data/opencv_sample_data/left03.jpg', 'calibration_data/opencv_sample_data/left06.jpg', 'calibration_data/opencv_sample_data/left07.jpg', 'calibration_data/opencv_sample_data/left04.jpg', 'calibration_data/opencv_sample_data/left02.jpg', 'calibration_data/opencv_sample_data/left12.jpg', 'calibration_data/opencv_sample_data/left14.jpg', 'calibration_data/opencv_sample_data/left09.jpg']


In [12]:
for i,fname in enumerate(images):

    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (7,6), None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)

        # Draw and display the corners
        cv.drawChessboardCorners(img, (7,6), corners2, ret)
        
        # cv.imshow('img', img)
        # cv.waitKey(500)
        # cv.destroyAllWindows()
        cv.imwrite("calibration_data/opencv_sample_data/"+str(i+1)+'.jpg', img)

        # # 转换颜色从 BGR 到 RGB，因为 OpenCV 使用 BGR 格式，而 matplotlib 使用 RGB
        # image_rgb = cv.cvtColor(img, cv.COLOR_BGR2RGB)
        # # 使用 matplotlib 显示图像
        # plt.imshow(image_rgb)
        # plt.axis('off')  # 不显示坐标轴
        # plt.show()
# cv.destroyAllWindows()

In [16]:
fname = images[0]
img = cv.imread(fname)
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
ret, corners = cv.findChessboardCorners(gray, (7,6), None)
print(len(corners))
print(corners)

42
[[[300.66736  350.92874 ]]

 [[288.1165   325.6781  ]]

 [[275.791    298.81805 ]]

 [[261.79785  269.80862 ]]

 [[248.05641  239.62509 ]]

 [[233.0008   206.92723 ]]

 [[217.46024  172.23552 ]]

 [[331.7006   344.225   ]]

 [[321.02307  318.99838 ]]

 [[309.01877  290.95587 ]]

 [[296.43378  261.66263 ]]

 [[283.09103  230.15082 ]]

 [[268.70892  196.34387 ]]

 [[253.59319  160.58485 ]]

 [[365.26065  337.42664 ]]

 [[354.58194  311.00723 ]]

 [[343.8793   282.5702  ]]

 [[331.7146   252.3243  ]]

 [[319.64725  219.97707 ]]

 [[306.20053  185.59566 ]]

 [[292.4419   149.10506 ]]

 [[398.1472   329.42392 ]]

 [[389.0941   302.81833 ]]

 [[379.35495  273.79822 ]]

 [[368.87122  242.77551 ]]

 [[357.2025   209.89412 ]]

 [[344.77472  174.81343 ]]

 [[331.92804  137.13455 ]]

 [[432.3794   321.51923 ]]

 [[424.3185   294.14877 ]]

 [[415.52548  264.92874 ]]

 [[405.9928   233.22798 ]]

 [[395.82507  199.43097 ]]

 [[384.8827   163.29341 ]]

 [[372.54977  125.020744]]

 [[466.34528  313

In [17]:
print(objp)

[[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [6. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [2. 1. 0.]
 [3. 1. 0.]
 [4. 1. 0.]
 [5. 1. 0.]
 [6. 1. 0.]
 [0. 2. 0.]
 [1. 2. 0.]
 [2. 2. 0.]
 [3. 2. 0.]
 [4. 2. 0.]
 [5. 2. 0.]
 [6. 2. 0.]
 [0. 3. 0.]
 [1. 3. 0.]
 [2. 3. 0.]
 [3. 3. 0.]
 [4. 3. 0.]
 [5. 3. 0.]
 [6. 3. 0.]
 [0. 4. 0.]
 [1. 4. 0.]
 [2. 4. 0.]
 [3. 4. 0.]
 [4. 4. 0.]
 [5. 4. 0.]
 [6. 4. 0.]
 [0. 5. 0.]
 [1. 5. 0.]
 [2. 5. 0.]
 [3. 5. 0.]
 [4. 5. 0.]
 [5. 5. 0.]
 [6. 5. 0.]]


In [19]:
corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
print(len(corners2))
print(corners2)

42
[[[300.39896  351.02505 ]]

 [[288.34534  325.87054 ]]

 [[275.4507   298.93454 ]]

 [[261.91742  270.2276  ]]

 [[247.81902  239.51468 ]]

 [[233.05627  206.82187 ]]

 [[217.51735  172.2564  ]]

 [[332.15152  344.51605 ]]

 [[320.8534   318.8697  ]]

 [[308.8871   290.95316 ]]

 [[296.25604  261.47534 ]]

 [[282.85373  230.01167 ]]

 [[268.6935   196.43626 ]]

 [[253.8891   160.65057 ]]

 [[364.86426  337.2962  ]]

 [[354.66214  311.0731  ]]

 [[343.66284  282.5844  ]]

 [[331.91318  252.43439 ]]

 [[319.5241   219.97514 ]]

 [[306.24716  185.598   ]]

 [[292.2811   148.7122  ]]

 [[398.34183  329.61322 ]]

 [[389.17358  302.77057 ]]

 [[379.3906   273.89566 ]]

 [[368.57544  242.93405 ]]

 [[357.27847  209.76617 ]]

 [[344.9039   174.39655 ]]

 [[331.88586  136.9367  ]]

 [[432.2574   321.65695 ]]

 [[424.35254  294.18613 ]]

 [[415.62024  264.70776 ]]

 [[406.15884  233.1491  ]]

 [[395.8562   199.32028 ]]

 [[384.6924   163.2047  ]]

 [[372.687    124.82221 ]]

 [[466.5723   313

In [3]:
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [20]:
print(mtx)

[[534.07088364   0.         341.53407554]
 [  0.         534.11914595 232.94565259]
 [  0.           0.           1.        ]]


In [21]:
print(dist)

[[-2.92971637e-01  1.07706962e-01  1.31038376e-03 -3.11018780e-05
   4.34798110e-02]]


In [22]:
print(rvecs)

(array([[ 0.30697385],
       [ 0.5038552 ],
       [-1.82824733]]), array([[-0.45883216],
       [-0.08848877],
       [-1.33510786]]), array([[-0.45993978],
       [-0.3142018 ],
       [-1.76122223]]), array([[-0.43239599],
       [ 0.25603401],
       [-3.08832021]]), array([[-0.2645143 ],
       [-0.39360849],
       [-2.74787379]]), array([[-0.29979221],
       [ 0.39216377],
       [-1.4348239 ]]), array([[-0.32034625],
       [ 0.1597993 ],
       [-1.24149595]]), array([[-0.37843358],
       [-0.18064237],
       [-3.11615996]]), array([[ 0.41531697],
       [ 0.65664497],
       [-1.3373494 ]]), array([[-0.35367631],
       [-0.24363035],
       [-1.56874295]]), array([[-0.17288944],
       [-0.46764681],
       [ 1.34745198]]))


In [23]:
print(tvecs )

(array([[-1.22339632],
       [ 3.52139948],
       [15.67311789]]), array([[-3.27916485],
       [ 2.15811689],
       [11.72833343]]), array([[-1.13991523],
       [ 2.67424464],
       [ 9.56289277]]), array([[ 3.79739146],
       [ 0.89895018],
       [14.8593055 ]]), array([[3.03685642],
       [2.74656588],
       [9.90005138]]), array([[ 1.60364763],
       [ 3.81296375],
       [16.12054474]]), array([[-5.94286695],
       [ 2.39629427],
       [16.77859026]]), array([[ 2.82321756],
       [ 2.22374307],
       [10.95762951]]), array([[-2.12419184],
       [ 1.84550818],
       [12.81229187]]), array([[-2.89985494],
       [ 2.62066993],
       [10.57699258]]), array([[ 1.81888151],
       [-4.2642919 ],
       [12.45728517]]))


In [4]:
img = cv.imread('calibration_data/opencv_sample_data/left12.jpg')
h,  w = img.shape[:2]
newcameramtx, roi = cv.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

In [5]:
# undistort
dst = cv.undistort(img, mtx, dist, None, newcameramtx)

# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult.png', dst)

True

In [6]:
# undistort
mapx, mapy = cv.initUndistortRectifyMap(mtx, dist, None, newcameramtx, (w,h), 5)
dst = cv.remap(img, mapx, mapy, cv.INTER_LINEAR)

# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult.png', dst)

True

In [7]:
mean_error = 0
for i in range(len(objpoints)):
    imgpoints2, _ = cv.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
    error = cv.norm(imgpoints[i], imgpoints2, cv.NORM_L2)/len(imgpoints2)
    mean_error += error

print( "total error: {}".format(mean_error/len(objpoints)) )

total error: 0.023686000375385673
