# Pinhole Camera Calibration
## 1. Introduction
### 1.1 Why Calibration?

### 1.2 How to Calibrate?
### 1.3 Calibrate results and how to use them?
## 2. Calibration principle
### 2.1 
## 3.Calibration process

In [1]:
import numpy as np
import cv2 as cv
import glob
import matplotlib.pyplot as plt
import os

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('calibration_data/opencv_sample_data/left*.jpg')
images = sorted(images)
print(images)


['calibration_data/opencv_sample_data/left01.jpg', 'calibration_data/opencv_sample_data/left02.jpg', 'calibration_data/opencv_sample_data/left03.jpg', 'calibration_data/opencv_sample_data/left04.jpg', 'calibration_data/opencv_sample_data/left05.jpg', 'calibration_data/opencv_sample_data/left06.jpg', 'calibration_data/opencv_sample_data/left07.jpg', 'calibration_data/opencv_sample_data/left08.jpg', 'calibration_data/opencv_sample_data/left09.jpg', 'calibration_data/opencv_sample_data/left11.jpg', 'calibration_data/opencv_sample_data/left12.jpg', 'calibration_data/opencv_sample_data/left13.jpg', 'calibration_data/opencv_sample_data/left14.jpg']


In [2]:
for i,fname in enumerate(images):

    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (7,6), None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)

        # Draw and display the corners
        cv.drawChessboardCorners(img, (7,6), corners2, ret)
        
        # cv.imshow('img', img)
        # cv.waitKey(500)
        # cv.destroyAllWindows()
        cv.imwrite("calibration_data/opencv_sample_data/"+str(i+1)+'.jpg', img)

        # # 转换颜色从 BGR 到 RGB，因为 OpenCV 使用 BGR 格式，而 matplotlib 使用 RGB
        # image_rgb = cv.cvtColor(img, cv.COLOR_BGR2RGB)
        # # 使用 matplotlib 显示图像
        # plt.imshow(image_rgb)
        # plt.axis('off')  # 不显示坐标轴
        # plt.show()
# cv.destroyAllWindows()

In [ ]:
fname = images[0]
print(fname)


calibration_data/opencv_sample_data/left01.jpg
42
[[[475.46497  264.59277 ]]

 [[440.46597  263.34772 ]]

 [[406.10455  261.65866 ]]

 [[372.7524   259.79944 ]]

 [[340.35718  258.2445  ]]

 [[308.5867   256.48032 ]]

 [[277.62714  255.30826 ]]

 [[476.7286   230.09175 ]]

 [[441.20877  228.56682 ]]

 [[406.42606  227.53233 ]]

 [[372.9427   226.42447 ]]

 [[339.5496   225.21759 ]]

 [[307.43317  224.24355 ]]

 [[276.82333  223.436   ]]

 [[477.29578  194.28926 ]]

 [[441.69385  193.79532 ]]

 [[406.95166  192.44704 ]]

 [[372.37253  191.89107 ]]

 [[339.1837   191.57596 ]]

 [[307.2744   191.09702 ]]

 [[275.79642  190.63934 ]]

 [[477.46838  158.28636 ]]

 [[442.083    157.73778 ]]

 [[406.68497  157.56912 ]]

 [[372.35477  157.37575 ]]

 [[338.70758  157.42206 ]]

 [[306.42056  157.61996 ]]

 [[275.37076  158.37704 ]]

 [[477.86743  122.10533 ]]

 [[441.9587   122.0216  ]]

 [[406.60403  122.157845]]

 [[372.09393  122.12903 ]]

 [[338.71494  123.26513 ]]

 [[306.04443  124.03228 ]]

In [ ]:
img = cv.imread(fname)
print(img)


[[[ 0  0  0]
  [ 2  2  2]
  [ 4  4  4]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 1  1  1]
  [ 2  2  2]
  [ 4  4  4]
  ...
  [ 4  4  4]
  [ 3  3  3]
  [ 6  6  6]]

 [[ 1  1  1]
  [ 3  3  3]
  [ 4  4  4]
  ...
  [ 6  6  6]
  [ 5  5  5]
  [ 3  3  3]]

 ...

 [[ 7  7  7]
  [38 38 38]
  [44 44 44]
  ...
  [56 56 56]
  [47 47 47]
  [11 11 11]]

 [[ 6  6  6]
  [35 35 35]
  [38 38 38]
  ...
  [43 43 43]
  [40 40 40]
  [ 8  8  8]]

 [[ 0  0  0]
  [12 12 12]
  [13 13 13]
  ...
  [12 12 12]
  [14 14 14]
  [ 0  0  0]]]


In [ ]:
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
print(gray)


[[ 0  2  4 ...  0  0  0]
 [ 1  2  4 ...  4  3  6]
 [ 1  3  4 ...  6  5  3]
 ...
 [ 7 38 44 ... 56 47 11]
 [ 6 35 38 ... 43 40  8]
 [ 0 12 13 ... 12 14  0]]


In [14]:
ret, corners = cv.findChessboardCorners(gray, (7,6), None)
print(len(corners))
print(corners)

42
[[[475.46497  264.59277 ]]

 [[440.46597  263.34772 ]]

 [[406.10455  261.65866 ]]

 [[372.7524   259.79944 ]]

 [[340.35718  258.2445  ]]

 [[308.5867   256.48032 ]]

 [[277.62714  255.30826 ]]

 [[476.7286   230.09175 ]]

 [[441.20877  228.56682 ]]

 [[406.42606  227.53233 ]]

 [[372.9427   226.42447 ]]

 [[339.5496   225.21759 ]]

 [[307.43317  224.24355 ]]

 [[276.82333  223.436   ]]

 [[477.29578  194.28926 ]]

 [[441.69385  193.79532 ]]

 [[406.95166  192.44704 ]]

 [[372.37253  191.89107 ]]

 [[339.1837   191.57596 ]]

 [[307.2744   191.09702 ]]

 [[275.79642  190.63934 ]]

 [[477.46838  158.28636 ]]

 [[442.083    157.73778 ]]

 [[406.68497  157.56912 ]]

 [[372.35477  157.37575 ]]

 [[338.70758  157.42206 ]]

 [[306.42056  157.61996 ]]

 [[275.37076  158.37704 ]]

 [[477.86743  122.10533 ]]

 [[441.9587   122.0216  ]]

 [[406.60403  122.157845]]

 [[372.09393  122.12903 ]]

 [[338.71494  123.26513 ]]

 [[306.04443  124.03228 ]]

 [[274.9684   124.752304]]

 [[477.623     86

In [4]:
print(objp)

[[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [6. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [2. 1. 0.]
 [3. 1. 0.]
 [4. 1. 0.]
 [5. 1. 0.]
 [6. 1. 0.]
 [0. 2. 0.]
 [1. 2. 0.]
 [2. 2. 0.]
 [3. 2. 0.]
 [4. 2. 0.]
 [5. 2. 0.]
 [6. 2. 0.]
 [0. 3. 0.]
 [1. 3. 0.]
 [2. 3. 0.]
 [3. 3. 0.]
 [4. 3. 0.]
 [5. 3. 0.]
 [6. 3. 0.]
 [0. 4. 0.]
 [1. 4. 0.]
 [2. 4. 0.]
 [3. 4. 0.]
 [4. 4. 0.]
 [5. 4. 0.]
 [6. 4. 0.]
 [0. 5. 0.]
 [1. 5. 0.]
 [2. 5. 0.]
 [3. 5. 0.]
 [4. 5. 0.]
 [5. 5. 0.]
 [6. 5. 0.]]


In [5]:
corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
print(len(corners2))
print(corners2)

42
[[[254.3047  308.90814]]

 [[253.28555 280.3951 ]]

 [[252.6328  248.56088]]

 [[251.75056 212.81516]]

 [[251.25952 172.68323]]

 [[251.0968  127.98352]]

 [[251.46336  78.19004]]

 [[293.6344  318.09045]]

 [[295.14844 289.76086]]

 [[296.85318 258.06537]]

 [[298.76303 222.35841]]

 [[301.10803 182.12656]]

 [[303.75592 136.99808]]

 [[307.06628  86.7118 ]]

 [[334.24542 327.16162]]

 [[338.0707  299.22272]]

 [[342.2667  267.76385]]

 [[347.08716 232.24538]]

 [[352.37762 192.20969]]

 [[358.42426 146.96033]]

 [[365.12714  96.77871]]

 [[375.2773  336.1042 ]]

 [[381.5933  308.35605]]

 [[388.45346 277.45508]]

 [[396.13586 242.3363 ]]

 [[404.6047  202.72343]]

 [[413.96667 157.7573 ]]

 [[424.13235 107.84622]]

 [[416.4308  344.54428]]

 [[425.23926 317.36096]]

 [[434.80084 286.7783 ]]

 [[445.2837  252.39128]]

 [[456.84183 213.54738]]

 [[469.5197  169.35127]]

 [[483.13724 120.09361]]

 [[456.9843  352.4336 ]]

 [[468.08008 325.7758 ]]

 [[480.23    296.07745]]

 [[493.46

In [6]:
gray.shape[::-1]

(640, 480)

In [8]:
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [9]:
print(mtx)

[[534.07088364   0.         341.53407552]
 [  0.         534.11914595 232.9456526 ]
 [  0.           0.           1.        ]]


In [10]:
print(dist)

[[-2.92971637e-01  1.07706962e-01  1.31038377e-03 -3.11018812e-05
   4.34798104e-02]]


In [ ]:
print(rvecs)

(array([[ 0.30697385],
       [ 0.5038552 ],
       [-1.82824733]]), array([[-0.45883216],
       [-0.08848877],
       [-1.33510786]]), array([[-0.45993978],
       [-0.3142018 ],
       [-1.76122223]]), array([[-0.43239599],
       [ 0.25603401],
       [-3.08832021]]), array([[-0.2645143 ],
       [-0.39360849],
       [-2.74787379]]), array([[-0.29979221],
       [ 0.39216377],
       [-1.4348239 ]]), array([[-0.32034625],
       [ 0.1597993 ],
       [-1.24149595]]), array([[-0.37843358],
       [-0.18064237],
       [-3.11615996]]), array([[ 0.41531697],
       [ 0.65664497],
       [-1.3373494 ]]), array([[-0.35367631],
       [-0.24363035],
       [-1.56874295]]), array([[-0.17288944],
       [-0.46764681],
       [ 1.34745198]]))


In [ ]:
print(tvecs )

(array([[-1.22339632],
       [ 3.52139948],
       [15.67311789]]), array([[-3.27916485],
       [ 2.15811689],
       [11.72833343]]), array([[-1.13991523],
       [ 2.67424464],
       [ 9.56289277]]), array([[ 3.79739146],
       [ 0.89895018],
       [14.8593055 ]]), array([[3.03685642],
       [2.74656588],
       [9.90005138]]), array([[ 1.60364763],
       [ 3.81296375],
       [16.12054474]]), array([[-5.94286695],
       [ 2.39629427],
       [16.77859026]]), array([[ 2.82321756],
       [ 2.22374307],
       [10.95762951]]), array([[-2.12419184],
       [ 1.84550818],
       [12.81229187]]), array([[-2.89985494],
       [ 2.62066993],
       [10.57699258]]), array([[ 1.81888151],
       [-4.2642919 ],
       [12.45728517]]))


In [ ]:
img = cv.imread('calibration_data/opencv_sample_data/left12.jpg')
h,  w = img.shape[:2]
newcameramtx, roi = cv.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

In [ ]:
# undistort
dst = cv.undistort(img, mtx, dist, None, newcameramtx)

# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult.png', dst)

True

In [ ]:
# undistort
mapx, mapy = cv.initUndistortRectifyMap(mtx, dist, None, newcameramtx, (w,h), 5)
dst = cv.remap(img, mapx, mapy, cv.INTER_LINEAR)

# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult.png', dst)

True

In [ ]:
mean_error = 0
for i in range(len(objpoints)):
    imgpoints2, _ = cv.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
    error = cv.norm(imgpoints[i], imgpoints2, cv.NORM_L2)/len(imgpoints2)
    mean_error += error

print( "total error: {}".format(mean_error/len(objpoints)) )

total error: 0.023686000375385673
